name: Build and Deploy world.html

on:
  push:
    branches:
      - '**'
    paths:
      - 'world.html'
  pull_request:
    branches:
      - '**'
    paths:
      - 'world.html'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Deploy to GitHub Pages
          if: ${{ github.ref == 'refs/heads/main' }}
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./